title: Ixchel Meza # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! My name is Ixchel and I am a Test Engineer. 
  <br><br>
  Charlotte, N.C.
  <br><br>
  <br/>I have a B.E. Information Technology and +8 years of experience in Software Testing.
  <br/>I love technology and I am passionate about learning. 
  <br/>I am certified as PSM I (Professional Scrum Master) and I currently studying a Masters in IT Management.
  <br/>
  <a href="https://www.linkedin.com/in/ixmeza/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
