title: Ixchel Meza # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello! My name is Ixchel and I am a Test Engineer in Charlotte, North Carolina. I have a B.E. Information Technology and +8 years of exp. in Software Testing.
  <br>
  <br> I love technology an I am always learning. Currently studying a Masters in IT Management. 
  <br> PSM I.
  <br>
  <a href="https://www.linkedin.com/in/ixmeza/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
